title: Blisko Siebie
email: kontakt@bliskosiebie.pl
description: "Coaching online dla rodziców adopcyjnych, rodziców zastępczych i osób przeciążonych emocjonalnie."
baseurl: "/blisko-siebie"
url: "https://bliskosiebie.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  posts:
    output: true

permalink: /:categories/:title/

sass:
  style: compressed
